# Generated by Django 3.2.6 on 2021-08-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('le_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('le_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
            },
        ),
    ]
