# Generated by Django 3.2.6 on 2021-08-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('pre_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('pre_hora_prestamo', models.TimeField(auto_now=True, verbose_name='Hora prestámo')),
                ('pre_hora_regreso', models.TimeField(verbose_name='Hora regreso')),
                ('pre_fecha', models.DateField(auto_now=True, verbose_name='Fechas')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.CreateModel(
            name='FichaPrestamo',
            fields=[
                ('fp_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fp_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo')),
            ],
            options={
                'verbose_name': 'Ficha de Préstamo',
                'verbose_name_plural': 'Fichas de Prestamo',
            },
        ),
    ]
