# Generated by Django 3.2.6 on 2021-08-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('ren_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ren_fecha_renta', models.DateField(auto_now=True, verbose_name='Fecha de renta')),
                ('ren_fecha_regreso', models.DateField(verbose_name='Fecha de regreso')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
            },
        ),
        migrations.CreateModel(
            name='FichaRenta',
            fields=[
                ('fr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fr_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renta.renta')),
            ],
            options={
                'verbose_name': 'Ficha de Renta',
                'verbose_name_plural': 'Fichas de Renta',
            },
        ),
    ]
