# Generated by Django 3.2.6 on 2021-08-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('mul_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('mul_monto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto de multa')),
                ('mul_descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('mul_estado', models.BooleanField(default=True, verbose_name='Estado de la multa')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
    ]
